### ISSUE TITLE
[FEATURE]: Monitor system.

### ISSUE THREAD

**Issue by dannysmc95** [Symbux/Turbo#26]
To implement some kind of plugin monitoring system that exposes an open WebSocket or UNIX socket for either an independent application or hostable as a web application that can monitor the status of commands, allow you to run commands, monitor read/writes to the database, and get a live log of all interactions happening.

This is pre-cursor to the docker container implementation, as I would also like to be able to offer multi-tenant hosted application for this.

**Comment by deathlynocturnal** [comment]
Project is deprecated, in favour of @sodacore/core project.
